### ISSUE TITLE
ImportError: cannot import name '_check_savefig_extra_args' from 'matplotlib.backend_bases' 

### ISSUE THREAD

**Issue by Weidong725** [ThomasBury/arfs#1]
When using leshy, it works normally, but it can't print out important pictures

**Comment by ThomasBury** [comment]
> When using leshy, it works normally, but it can't print out important pictures

Hi,
which version of `matplotlib` are you using? And are you using jupyter? You might need to update both.

if you are using pip:
```bash
pip uninstall matplotlib
pip install --upgrade matplotlib
```

```bash
pip install -U jupyter
```

or if you are using conda:

```bash
conda uninstall matplotlib
conda install  matplotlib
```

```bash
conda update jupyter
```

**Comment by Weidong725** [comment]
Thank you. It's really a problem with the Matplotlib version
