### ISSUE TITLE
GrootCV: Extracting average SHAP over all iterations *per sample* in addition to per feature

### ISSUE THREAD

**Issue by bobby-slavchev** [ThomasBury/arfs#14]
I'd like to use GrootCV not only for feature selection, but also for data mining. Specifically, what I'm lacking is a way to see how each feature influenced the prediction for **each sample** over the iterations. I have been using SHAP for that purpose until now, but the estimates can be a little noisy, or at least I fear so. 

Similarly to how I can get the full history of overall importance per feature using GrootCV.cv_df - would it be possible to also surface the impact per feature, per sample, per iteration? That way I can build statistical confidence on each feature's impact on each sample.

**Comment by ThomasBury** [comment]
Hi @bobby-slavchev, If you need only to x-val SHAP values (per-sample/local), you can do it easily using a for loop as in [this google colab NB](https://colab.research.google.com/drive/1icEsSxTLtDn9_3PhQkjxVY7j25jcqRhM?usp=sharing)

Do you need to compare it to the local SHAP value for the shadow version? I don't know how this comparison would be useful for data mining though.
