### ISSUE TITLE
potential to specify time series splitter

### ISSUE THREAD

**Issue by almostintuitive** [ThomasBury/arfs#23]
Hi! Thank you for the super useful library!
We'd love to use it on time series tasks, but for that, we'd need the internal splitter to respect the temporal dimension of the data.
We're happy to contribute a PR that makes this possible.
Is there anything specific regarding the public API that we should keep in mind of, in order for our PR to be accepted?

Thank you!

**Comment by Jnorm911** [comment]
Bump

**Comment by CMobley7** [comment]
Optuna's implementation here, https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTunerCV.html,  allows you to send in your own folds; so,
```
tscv = TimeSeriesSplit(n_splits=cv if cv is not None else 5)
folds = list(tscv.split(X_train))
```
Though mlxtend's SFS, https://rasbt.github.io/mlxtend/api_subpackages/mlxtend.feature_selection/#sequentialfeatureselector, allows you to use TimeSeriesSplit directly with the cv argument. Optuna's would probably be a quick add, while mlxtend's would likely take longer to add. Not sure though.

**Comment by notuntoward** [comment]
Tabular methods are very commonly used for time series forecasting -- boosted trees are quite often the best time series forecasting methods available.  So it would be very useful if ARFS had a way to specify causal cross-validation.

As @CMobley mentioned, optuna allows causal cross validation, and so does the tuner I use with boosted trees, scikit-optimize.  For example, [skopt.BayesSearchCV](https://scikit-optimize.github.io/stable/modules/generated/skopt.BayesSearchCV.html) accepts a standard sklearn TimeSeriesSplit object.

Would be great if ARFS function did too.

**Comment by ThomasBury** [comment]
Hello, I finally had time to add support for user-defined splitter https://github.com/ThomasBury/arfs/commit/3771d499f8dbc572ad4d9a7df740c38e0616bd61

**Comment by notuntoward** [comment]
Thanks, should we be seeing this change on the website docs yet, or in pip?

**Comment by ThomasBury** [comment]
> Thanks, should we be seeing this change on the website docs yet, or in pip?

Hi @notuntoward , both:

- documentation:
https://arfs.readthedocs.io/en/latest/notebooks/arfs_timeseries.html

- release ARFS 2.3.0: https://pypi.org/project/arfs/
