### ISSUE TITLE
GrootCV is missing class_weight param for muticlass classification

### ISSUE THREAD

**Issue by blueoceancruiser** [ThomasBury/arfs#25]
Thank you for this wonderful package. It must have been a lot of research and hard work to address so many issues with the older packages!  I don't have the expertise to give you a PR but I did noted this:

LightGBM has a class_weight parameter for unbalanced classes that seems to be missing in GrootCV.  One can set the objective to multiclass, but there is then no way to enter the corresponding class_weight parameter, resulting in LightGBM giving a warning that the classes are unbalanced.

**Comment by ThomasBury** [comment]
Thank you for the kind words @blueoceancruiser. 
In the current version, I implemented a very [basic strategy](https://github.com/ThomasBury/arfs/blob/f051632fee1f51d83128471d7fa41ac37bec295c/src/arfs/feature_selection/allrelevant.py#L2224):

```python
        if main_class > 0.8:
            param.update({"is_unbalance": True})
```

In this strategy, if the main class represents more than 80% of the events, the behavior is switched to the "unbalanced" mode using the is_unbalance parameter from LightGBM. However, I acknowledge that this approach may not be ideal, as the positive weight may generally be too large. 

Alternatively, I could remove this logic and allow the user to set up the appropriate sample_weight vector according to their specific needs (achieving the same effect as using a `class_weight`). It's a trade-off between automation and flexibility.
