### ISSUE TITLE
Numba

### ISSUE THREAD

**Issue by blueoceancruiser** [ThomasBury/arfs#26]
This is minor, but I wanted to note it in case you haven't seen it yourself.  I'm getting this warning when I run GrootCV:  

The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

**Comment by ThomasBury** [comment]
Hi @blueoceancruiser , it could be because you're using python 3.11, not supported yet by numba. Try using python <3.11. I modified the requirements. Thanks for pointing that out.
