### ISSUE TITLE
Consider using FastTreeSHAP?

### ISSUE THREAD

**Issue by almostintuitive** [ThomasBury/arfs#27]
https://engineering.linkedin.com/blog/2022/fasttreeshap--accelerating-shap-value-computation-for-trees
It looks like it's a drop-in replacement, which we'll start testing next week!

**Comment by ThomasBury** [comment]
Great, I'll take a look! I remember reading the paper in 2021, but I've forgotten most of its contents and I wasn't aware of its python implementation.

**Comment by almostintuitive** [comment]
We have been using FastTreeSharp for over a month now, has excellent performance and is an order of mangitude smaller library than `shap`, which is for some reason, huge. the API is exactly the same, we definitely recommend switching over!

**Comment by almostintuitive** [comment]
sorry @ThomasBury , it was most probably a PR opened by mistake. our focus has shifted quite a bit, and we're not currently using Groot/Leshy. Hopefully we'll get back to it soon, and be able to contribute.
