### ISSUE TITLE
arfs.feature_selection module not found

### ISSUE THREAD

**Issue by xdeltadev** [ThomasBury/arfs#29]
ModuleNotFoundError: no module named feature_selection

**Comment by ThomasBury** [comment]
Hi @xdeltadev. To better understand and address the issue you are facing, could you please provide additional context and a minimal example that can help me reproduce the error? Also, please note that if you are using the latest version, there should not be an import error.

![image](https://github.com/ThomasBury/arfs/assets/28918551/8390efb4-8150-411f-a5ba-16768e892621)

**Comment by xdeltadev** [comment]
Sorry for the vague issue. Using Python 3.7, I recreated the issue using a clean conda environment. 


# from IPython.core.display import display, HTML
# display(HTML("<style>.container { width:95% !important; }</style>"))
import catboost
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import gc
import shap
from boruta import BorutaPy as bp
from sklearn.datasets import fetch_openml
from sklearn.inspection import permutation_importance
from sklearn.pipeline import Pipeline
from sklearn.datasets import fetch_openml
from sklearn.inspection import permutation_importance
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from lightgbm import LGBMRegressor, LGBMClassifier
from xgboost import XGBRegressor, XGBClassifier
from catboost import CatBoostRegressor, CatBoostClassifier
from sys import getsizeof, path

import arfs
import arfs.feature_selection as arfsfs
import arfs.feature_selection.allrelevant as arfsgroot
from arfs.feature_selection import (
    MinRedundancyMaxRelevance,
    GrootCV,
    MissingValueThreshold,
    UniqueValuesThreshold,
    CollinearityThreshold,
    make_fs_summary,
)
from arfs.utils import LightForestClassifier, LightForestRegressor
from arfs.benchmark import highlight_tick, compare_varimp, sklearn_pimp_bench
from arfs.utils import load_data

plt.style.use("fivethirtyeight")
rng = np.random.RandomState(seed=42)

# import warnings
# warnings.filterwarnings('ignore')


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_21744\3187753728.py in <module>
     22 
     23 import arfs
---> 24 import arfs.feature_selection as arfsfs
     25 import arfs.feature_selection.allrelevant as arfsgroot
     26 from arfs.feature_selection import (

ModuleNotFoundError: No module named 'arfs.feature_selection'

**Comment by ThomasBury** [comment]
Dear @xdeltadev , this is because you are using python==3.7, so pip install arfs version 0.3 (because of the dependencies). Please use python 3.10 and it should be fine.

I'll update the requirements to prevent dependency issues.
