### ISSUE TITLE
Cannot suppress runtime warning

### ISSUE THREAD

**Issue by mberlinger3** [ThomasBury/arfs#30]
I keep getting the warning below when using the pipeline filtering methods but it cannot be suppressed using np.seterr() or a warning filter

```
/lib/python3.10/site-packages/arfs/association.py:715: RuntimeWarning: invalid value encountered in scalar divide
  return wcov(x, y, w)/ np.sqrt(wcov(x, x, w) * wcov(y, y, w))
```

**Comment by ThomasBury** [comment]
Hi @mberlinger3, can you provide a minimal example? It might be because you are using a singular matrix.
