### ISSUE TITLE
LightGBM bump and folds var

### ISSUE THREAD

**Issue by CMobley7** [ThomasBury/arfs#32]
Thanks for a great library! I'm just starting to look through the code more in-depth now. Given that Optuna v3.3.0 supports LightGBM v4.0.0, is it possible to bump those in the setup.py? I see that as the reason for the downgrade to 3.3.1 here, https://github.com/ThomasBury/arfs/releases/tag/2.0.6. LightGBM 4.0 adds some nice to have, such as native GPU support. However, FastTreeSHAP doesn't support past version 3.3.5 atm; so that would need to default to False; otherwise, you'd get the following error: https://github.com/linkedin/FastTreeSHAP/issues/19. Also, out of curiosity, how hard would it be to allow the user to send in their own folds like Optuna's LGBM implementation, https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTunerCV.html? I work on a variety of different problem domains and time series is one of them and the problem in which I'm currently trying to solve.

**Comment by CMobley7** [comment]
It looks like the folds param could be added nicely to this function: https://github.com/ThomasBury/arfs/blob/main/src/arfs/feature_selection/allrelevant.py#L2188. Also, using fasttreeshap already defaults to false. Would you accept a PR that did these two things?

**Comment by ThomasBury** [comment]
Hello @CMobley7,

I plan to examine the latest version of Optuna to determine if it now supports the most recent LightGBM version. As you mentioned, FastTreeShap currently does not support the latest LightGBM version and encounters additive check errors, which means it cannot accurately match the target value using the SHAP linear approximation.

You can explore the GPU option at https://arfs.readthedocs.io/en/latest/notebooks/arfs_on_GPU.html.

Regarding the folds, while it shouldn't be too difficult, it will still require some effort and refactoring. I'll dedicate time to this task when I have the opportunity.

Best regards.

**Comment by ThomasBury** [comment]
The folds can now be user-defined https://github.com/ThomasBury/arfs/commit/3771d499f8dbc572ad4d9a7df740c38e0616bd61
