### ISSUE TITLE
Bug: MinRedundancyMaxRelevance Function Modifies Input DataFrame by Adding target Column

### ISSUE THREAD

**Issue by Pacman1984** [ThomasBury/arfs#39]
## Description
The `MinRedundancyMaxRelevancy` class adds the `target` column to `X`. 

## Steps to Reproduce
1. Import the `MinRedundancyMaxRelevancy` class 
2. Create a DataFrame `X` and a target series `y`.
3. Call the `MinRedundancyMaxRelevancy` fit function with `X` and `y` as inputs.
4. Observe that the `target` column is unexpectedly added to DataFrame `X`.

## Expected Behavior
The ``MinRedundancyMaxRelevancy` fit method should compute the necessary values and return them without modifying the input DataFrame `X`.

## Actual Behavior
The input DataFrame `X` is being modified by having the `target` column appended to it after calling  `MinRedundancyMaxRelevancy` fit method.
![image](https://github.com/ThomasBury/arfs/assets/14351072/efd51491-443c-41ed-a6c3-316cc40ba447)

**Comment by Pacman1984** [comment]
This is not happening with a custom relevance_func and redundancy_func setup

**Comment by ThomasBury** [comment]
Good catch, I added the missing `copy()` to prevent modifying the input pandas DF when fitting the selector
