### ISSUE TITLE
Duplicated feature importance columns in reduce_vars_sklearn

### ISSUE THREAD

**Issue by AndreaVidali** [ThomasBury/arfs#43]
Hello, I was analyzing the source code of BoostAGroota, and I noticed a couple of strange things. I will show the first here, and the other in another issue to keep things tidy.

In  [src/arfs/feature_selection/allrelevant.py](https://github.com/ThomasBury/arfs/blob/main/src/arfs/feature_selection/allrelevant.py) in function `_reduce_vars_sklearn` there is this piece of code: 

```python
        if i == 1:
            df = pd.DataFrame({"feature": new_x.columns})
            df2 = df.copy()

        # Store the feature importances in df2
        try:
            # Normalize the feature importances
            df2["fscore" + str(i)] = importance / importance.sum()
        except ValueError:
            print("Only Sklearn tree based methods allowed")

        # Merge the current feature importances with the existing ones in df
        df = pd.merge(
            df, df2, on="feature", how="outer", suffixes=("_x" + str(i), "_y" + str(i))
        )
```

The issue is about the `pd.merge`: I noticed that, over `n_iterations`, it duplicates the feature importances of previous iterations because the same importance is present in both `df` and `df2`. 

After `n_iterations`, I expect a dataframe of importance data of shape `len(real_vars) + len(shadow_vars)` x `n_iterations`, but instead the number of columns is way higher due to the `pd.merge`. As a result, the average importances calculated with`df["Mean"] = df.select_dtypes(include=[np.number]).mean(axis=1, skipna=True)` will be slightly biased by the repeated columns.

You can check this behavior by comparing `df` and `df2` right after the `for` loop. You will see that `df` has way too many columns, while `df2` has the correct number of columns.

I hope I have described the problem well enough. Let me know what you think.

**Comment by ThomasBury** [comment]
Hi @AndreaVidali thank you for the careful review. You're right, I missed correcting that bug when building on top of BoostARoota. No need to copy and merge, a simple update of the DF works.

Fixed by https://github.com/ThomasBury/arfs/commit/945d8fc55692d627497796bc26df5935ec734825

**Comment by AndreaVidali** [comment]
Wonderful, thanks!
