### ISSUE TITLE
Max on the wrong axis in _reduce_vars_sklearn

### ISSUE THREAD

**Issue by AndreaVidali** [ThomasBury/arfs#44]
Hello, I think I found a possible bug in [src/arfs/feature_selection/allrelevant.py](https://github.com/ThomasBury/arfs/blob/main/src/arfs/feature_selection/allrelevant.py), in function `_reduce_vars_sklearn`:

```python
    # Get mean value from the shadows (max, like in Boruta, median to mitigate variance)
    mean_shadow = (
        shadow_vars.select_dtypes(include=[np.number])
        .max(skipna=True)
        .mean(skipna=True)
        / cutoff
    )
```

The bug is about `max`, which should have `axis=1`. Without it, It takes the maximum shap of all features, for each iteration. But I would expect the contrary, which is the maximum shap of all iteration, for each feature.

I may be wrong here, but I had to ask. Thank you!

Side note: probably that comment above the function is outdated :)

**Comment by ThomasBury** [comment]
Hi @AndreaVidali,

Thank you for your thorough review; I appreciate it. You're correct, the axis=1 argument is missing.That will be corrected in the next release.

In the original version, `.mean(axis=1).mean()` was used. I opted for a more aggressive approach with `.max(axis=1).mean()` in the current iteration.

**Comment by ThomasBury** [comment]
Solved by https://github.com/ThomasBury/arfs/commit/945d8fc55692d627497796bc26df5935ec734825

**Comment by AndreaVidali** [comment]
Thanks @ThomasBury I am glad to help!
